const APP_VERSION='0.4';
const PATCH_NOTES={version:'0.4',date:'19.08.2026',title:'Beta 0.4 – Probelauf',notes:['Probelauf des automatischen Update-Systems gestartet.','Wenn du diese Patchnotes auf dem Handy siehst, hat die automatische Aktualisierung funktioniert.','Alle gespeicherten Grundstücksdaten bleiben unverändert erhalten.']};
const PILOT_REGIONS=['Basel-Stadt','Basel-Landschaft','Aargau','Solothurn'];
const state={items:JSON.parse(localStorage.getItem('structaScoutItems')||'[]')};
const fmt=n=>new Intl.NumberFormat('de-CH',{style:'currency',currency:'CHF',maximumFractionDigits:0}).format(n);
const fmtNum=n=>new Intl.NumberFormat('de-CH').format(n);
const scoreOf=x=>{if(x.status==='web')return null;const invest=x.price+x.build+x.extra;const profit=x.revenue-invest;const margin=invest>0?profit/invest*100:0;const econ=Math.max(0,Math.min(100,margin*4));return Math.round(econ*.4+x.location*.25+x.planning*.2+x.risk*.15)};
const enrich=x=>{if(x.status==='web')return {...x,invest:x.price,profit:null,margin:null,score:null};const invest=x.price+x.build+x.extra;const profit=x.revenue-invest;const margin=invest?profit/invest*100:0;return {...x,invest,profit,margin,score:scoreOf(x)}};
const save=()=>localStorage.setItem('structaScoutItems',JSON.stringify(state.items));
const $=id=>document.getElementById(id);
function showPatchNotes(){const seen=localStorage.getItem('structaScoutSeenVersion');if(seen===APP_VERSION)return;$('patchTitle').textContent=`Was ist neu in ${PATCH_NOTES.title}?`;$('patchDate').textContent=PATCH_NOTES.date;$('patchNotes').innerHTML=PATCH_NOTES.notes.map(n=>`<div class="patch-item"><span>✓</span><p>${n}</p></div>`).join('');$('patchDialog').showModal();}
function markPatchSeen(){localStorage.setItem('structaScoutSeenVersion',APP_VERSION);$('patchDialog').close();}
async function registerUpdates(){if(!('serviceWorker' in navigator))return;try{const reg=await navigator.serviceWorker.register('./sw.js?v='+APP_VERSION);const trigger=()=>reg.update().catch(()=>{});trigger();document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')trigger()});window.addEventListener('focus',trigger);navigator.serviceWorker.addEventListener('controllerchange',()=>{if(sessionStorage.getItem('structaScoutReloading'))return;sessionStorage.setItem('structaScoutReloading','1');$('updateStatus').hidden=false;setTimeout(()=>location.reload(),250)});setInterval(trigger,15*60*1000);}catch(e){console.warn('Update-Prüfung nicht verfügbar',e)}}
function render(){let items=state.items.filter(x=>PILOT_REGIONS.includes(x.region)).map(enrich);const region=$('regionFilter').value,budget=+$('budgetFilter').value*1e6,strat=$('strategyFilter').value,minMargin=+$('marginFilter').value;items=items.filter(x=>(region==='all'||x.region===region)&&(strat==='all'||x.strategy===strat)&&x.price<=budget&&(x.margin===null?minMargin===0:x.margin>=minMargin));const sort=$('sortFilter').value;items.sort((a,b)=>{if(sort==='price')return a.price-b.price;const av=a[sort]??-Infinity,bv=b[sort]??-Infinity;return bv-av});$('countKpi').textContent=items.length;const analysed=items.filter(x=>x.status!=='web');$('marginKpi').textContent=analysed.length?(analysed.reduce((s,x)=>s+x.margin,0)/analysed.length).toFixed(1)+' %':'offen';$('profitKpi').textContent=analysed.length?fmt(analysed.reduce((s,x)=>s+x.profit,0)/analysed.length):'offen';const scored=analysed.filter(x=>x.score!==null);const best=scored.length?Math.max(...scored.map(x=>x.score)):null;$('scoreKpi').textContent=best??'–';$('topScore').textContent=best??'–';$('list').innerHTML=items.length?items.map(x=>{if(x.status==='web')return `<article class="card web-card"><div><div class="source-row"><span class="source-badge">WEB-FUND</span><span class="found-date">gefunden ${x.found}</span></div><h4>${x.name}</h4><div class="meta"><span>${x.region}</span><span>${x.strategy}</span><span>${fmtNum(x.area)} m²</span><span>${fmt(Math.round(x.price/x.area))}/m²</span></div><div class="metrics"><span class="metric">Kaufpreis<strong>${fmt(x.price)}</strong></span><span class="metric">Baukosten<strong>noch offen</strong></span><span class="metric">Gewinn<strong>noch offen</strong></span><span class="metric">Marge<strong>noch offen</strong></span></div><div class="web-actions"><span>Quelle: ${x.source}</span>${x.url?`<a href="${x.url}" target="_blank" rel="noopener noreferrer">Inserat öffnen ↗</a>`:''}</div></div><div class="score pending"><strong>?</strong><small>VORPRÜFUNG</small></div></article>`;return `<article class="card"><div><h4>${x.name}</h4><div class="meta"><span>${x.region}</span><span>${x.strategy}</span><span>${fmtNum(x.area)} m²</span></div><div class="metrics"><span class="metric">Kaufpreis<strong>${fmt(x.price)}</strong></span><span class="metric">Investition<strong>${fmt(x.invest)}</strong></span><span class="metric">Gewinn<strong>${fmt(x.profit)}</strong></span><span class="metric">Marge<strong>${x.margin.toFixed(1)} %</strong></span></div></div><div class="score"><strong>${x.score}</strong><small>SCORE</small></div></article>`}).join(''):'<div class="empty"><strong>Noch keine passenden Grundstücke</strong><p>Web-Test laden oder ein Grundstück erfassen.</p></div>'}
function demo(){state.items=[{name:'Riehen BS · Bauland',region:'Basel-Stadt',strategy:'Offen / Vorprüfung',area:784,price:1825000,status:'web',source:'ImmoScout24',found:'19.08.2026',url:'https://www.immoscout24.ch/de/grundstueck/kaufen/kanton-basel-stadt'},{name:'Rümlingen BL · Bauland',region:'Basel-Landschaft',strategy:'Offen / Vorprüfung',area:2024,price:949000,status:'web',source:'ImmoScout24',found:'19.08.2026',url:'https://www.immoscout24.ch/de/grundstueck/kaufen/kanton-basel-landschaft'},{name:'Frick AG · Bauland',region:'Aargau',strategy:'Offen / Vorprüfung',area:646,price:798000,status:'web',source:'ImmoScout24',found:'19.08.2026',url:'https://www.immoscout24.ch/de/grundstueck/kaufen/kanton-aargau'},{name:'Oberdorf SO · Bauland',region:'Solothurn',strategy:'Offen / Vorprüfung',area:605,price:680000,status:'web',source:'ImmoScout24',found:'19.08.2026',url:'https://www.immoscout24.ch/de/grundstueck/kaufen/kanton-solothurn'}];save();render()}
$('demoBtn').addEventListener('click',demo);$('addBtn').addEventListener('click',()=>$('dialog').showModal());$('closeBtn').addEventListener('click',()=>$('dialog').close());$('cancelBtn').addEventListener('click',()=>$('dialog').close());$('patchCloseBtn').addEventListener('click',markPatchSeen);$('resetBtn').addEventListener('click',()=>{$('regionFilter').value='all';$('budgetFilter').value='999';$('strategyFilter').value='all';$('marginFilter').value='0';render()});['regionFilter','budgetFilter','strategyFilter','marginFilter','sortFilter'].forEach(id=>$(id).addEventListener('change',render));$('form').addEventListener('submit',e=>{e.preventDefault();const region=$('region').value;if(!PILOT_REGIONS.includes(region)){alert('Aktuell sind nur Basel-Stadt, Basel-Landschaft, Aargau und Solothurn als Pilotregionen freigeschaltet.');return;}state.items.unshift({name:$('name').value.trim(),region,strategy:$('strategy').value,area:+$('area').value,price:+$('price').value,build:+$('build').value,extra:+$('extra').value,revenue:+$('revenue').value,location:+$('location').value,planning:+$('planning').value,risk:+$('risk').value,status:'analysed'});save();e.target.reset();$('dialog').close();render()});
$('appVersion').textContent='Beta '+APP_VERSION;render();showPatchNotes();registerUpdates();