const APP_VERSION='0.8';
const BACKEND='https://structa-scout-backend.vercel.app/api/search';
const PATCH_NOTES={version:'0.8',date:'19.08.2026',title:'Beta 0.8 – Chef-Version',notes:['Markt- und Wirtschaftlichkeitscheck vollständig überarbeitet.','Neue Kennzahlen: Gesamtinvestition, Erlös, Gewinn, Marge, Break-even-Verkaufspreis und maximal tragbarer Grundstückspreis.','Klare Empfehlung KAUFEN / VERTIEFEN / NICHT KAUFEN.','Investment Score berücksichtigt Wirtschaftlichkeit, Markt, Baurecht, Architekturpotenzial und Risiko.','Kostenloser Live-Web-Scan mit acht kostenlosen Fallback-Suchbereichen ergänzt.','Präsentations-Beispielanalyse ergänzt. 0 CHF laufende Softwarekosten bleiben oberste Vorgabe.']};
const PILOT_REGIONS=['Basel-Stadt','Basel-Landschaft','Aargau','Solothurn'];
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=n=>new Intl.NumberFormat('de-CH',{style:'currency',currency:'CHF',maximumFractionDigits:0}).format(Number(n)||0);
const num=n=>new Intl.NumberFormat('de-CH',{maximumFractionDigits:0}).format(Number(n)||0);
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
const loaded=JSON.parse(localStorage.getItem('structaScoutItems')||'[]');
const state={items:loaded.filter(x=>!['Riehen BS · Bauland','Rümlingen BL · Bauland','Frick AG · Bauland','Oberdorf SO · Bauland'].includes(x.name))};
const save=()=>localStorage.setItem('structaScoutItems',JSON.stringify(state.items));
if(state.items.length!==loaded.length)save();

function calculate(x){
  if(x.status==='web')return {...x,score:null,margin:null,profit:null};
  if(x.gfa&&x.sellable&&x.saleM2&&x.buildM2){
    const build=x.gfa*x.buildM2;
    const soft=build*(x.softPct/100);
    const reserve=build*(x.reservePct/100);
    const acq=x.price*(x.acqPct/100);
    const other=build+soft+reserve;
    const invest=x.price+acq+other;
    const revenue=x.sellable*x.saleM2;
    const profit=revenue-invest;
    const margin=invest?profit/invest*100:0;
    const breakEven=x.sellable?invest/x.sellable:0;
    const marketBuffer=x.saleM2?((x.saleM2-breakEven)/x.saleM2)*100:0;
    const target=(x.targetMargin||15)/100;
    const maxLand=Math.max(0,(revenue/(1+target)-other)/(1+(x.acqPct/100)));
    const econ=clamp((margin+5)*4);
    const market=clamp(50+marketBuffer*2);
    const score=Math.round(econ*.35+market*.25+(+x.planning||50)*.15+(+x.architecture||60)*.10+(+x.risk||50)*.15);
    let decision='VERTIEFEN',decisionClass='check',reason='Potenzial vorhanden, Annahmen und Baurecht vertiefen.';
    if(margin>=15&&marketBuffer>=8&&score>=70){decision='KAUFEN';decisionClass='buy';reason='Wirtschaftlichkeit, Marktpuffer und Gesamtscore liegen im attraktiven Bereich.'}
    else if(margin<8||marketBuffer<0||score<50){decision='NICHT KAUFEN';decisionClass='no';reason='Aktuelle Annahmen ergeben zu wenig Marge, Marktpuffer oder Gesamtscore.'}
    return {...x,build,soft,reserve,acq,invest,revenue,profit,margin,breakEven,marketBuffer,maxLand,score,decision,decisionClass,reason};
  }
  const invest=(+x.price||0)+(+x.build||0)+(+x.extra||0);const revenue=+x.revenue||0;const profit=revenue-invest;const margin=invest?profit/invest*100:0;const econ=clamp((margin+5)*4);const score=Math.round(econ*.4+(+x.location||60)*.25+(+x.planning||60)*.2+(+x.risk||60)*.15);return {...x,invest,revenue,profit,margin,score,decision:margin>=15?'KAUFEN':margin>=8?'VERTIEFEN':'NICHT KAUFEN',decisionClass:margin>=15?'buy':margin>=8?'check':'no',reason:'Alte Berechnung – für volle Marktprüfung erneut öffnen.'};
}

function showPatchNotes(){if(localStorage.getItem('structaScoutSeenVersion')===APP_VERSION)return;$('patchTitle').textContent=`Was ist neu in ${PATCH_NOTES.title}?`;$('patchDate').textContent=PATCH_NOTES.date;$('patchNotes').innerHTML=PATCH_NOTES.notes.map(n=>`<div class="patch-item"><span>✓</span><p>${esc(n)}</p></div>`).join('');$('patchDialog').showModal()}
function markPatchSeen(){localStorage.setItem('structaScoutSeenVersion',APP_VERSION);$('patchDialog').close()}
async function registerUpdates(){if(!('serviceWorker'in navigator))return;try{const reg=await navigator.serviceWorker.register('./sw.js?v='+APP_VERSION);reg.update().catch(()=>{});document.addEventListener('visibilitychange',()=>document.visibilityState==='visible'&&reg.update().catch(()=>{}));window.addEventListener('focus',()=>reg.update().catch(()=>{}));navigator.serviceWorker.addEventListener('controllerchange',()=>{if(sessionStorage.getItem('structaScoutReloading'))return;sessionStorage.setItem('structaScoutReloading','1');$('updateStatus').hidden=false;setTimeout(()=>location.reload(),250)})}catch(e){console.warn(e)}}

function formData(){return {name:$('name').value.trim(),region:$('region').value,strategy:$('strategy').value,area:+$('area').value,price:+$('price').value,gfa:+$('gfa').value,sellable:+$('sellable').value,saleM2:+$('saleM2').value,buildM2:+$('buildM2').value,softPct:+$('softPct').value,reservePct:+$('reservePct').value,acqPct:+$('acqPct').value,targetMargin:+$('targetMargin').value,location:+$('location').value,planning:+$('planning').value,architecture:+$('architecture').value,risk:+$('risk').value,status:'analysed',updated:new Date().toISOString()}}
function updatePreview(){if(!$('previewCalc'))return;const x=calculate(formData());$('previewCalc').innerHTML=`<div class="preview-grid"><div><span>Gesamtinvestition</span><strong>${fmt(x.invest)}</strong></div><div><span>Verkaufserlös</span><strong>${fmt(x.revenue)}</strong></div><div><span>Gewinn</span><strong>${fmt(x.profit)}</strong></div><div><span>Projektmarge</span><strong>${x.margin.toFixed(1)} %</strong></div><div><span>Break-even Verkauf</span><strong>${fmt(x.breakEven)}/m²</strong></div><div><span>Marktpuffer</span><strong>${x.marketBuffer.toFixed(1)} %</strong></div><div><span>Max. Grundstückspreis</span><strong>${fmt(x.maxLand)}</strong></div><div><span>Investment Score</span><strong>${x.score}/100</strong></div></div><div class="recommendation ${x.decisionClass}">${x.decision} · ${esc(x.reason)}</div>`}

function render(){let items=state.items.map(calculate).filter(x=>PILOT_REGIONS.includes(x.region));const region=$('regionFilter').value,budget=+$('budgetFilter').value*1e6,strat=$('strategyFilter').value,min=+$('marginFilter').value;items=items.filter(x=>(region==='all'||x.region===region)&&(strat==='all'||x.strategy===strat)&&(+x.price||0)<=budget&&(x.margin==null?min===0:x.margin>=min));const sort=$('sortFilter').value;items.sort((a,b)=>sort==='price'?(a.price-b.price):((b[sort]??-Infinity)-(a[sort]??-Infinity)));$('countKpi').textContent=items.length;const analysed=items.filter(x=>x.margin!=null);$('marginKpi').textContent=analysed.length?(analysed.reduce((s,x)=>s+x.margin,0)/analysed.length).toFixed(1)+' %':'offen';$('profitKpi').textContent=analysed.length?fmt(analysed.reduce((s,x)=>s+x.profit,0)/analysed.length):'offen';const best=analysed.length?Math.max(...analysed.map(x=>x.score||0)):null;$('scoreKpi').textContent=best??'–';$('topScore').textContent=best??'–';$('list').innerHTML=items.length?items.map(x=>`<article class="card deal-card"><div><div class="deal-top"><span class="decision-chip ${x.decisionClass}">${x.decision}</span><h4>${esc(x.name)}</h4></div><div class="meta"><span>${esc(x.region)}</span><span>${esc(x.strategy)}</span><span>${num(x.area)} m² Grundstück</span>${x.gfa?`<span>${num(x.gfa)} m² BGF</span>`:''}</div><div class="metrics"><span class="metric">Kaufpreis<strong>${fmt(x.price)}</strong></span><span class="metric">Investition<strong>${fmt(x.invest)}</strong></span><span class="metric">Gewinn<strong>${fmt(x.profit)}</strong></span><span class="metric">Marge<strong>${x.margin.toFixed(1)} %</strong></span></div>${x.breakEven?`<div class="deal-details"><div><span>Marktannahme</span><strong>${fmt(x.saleM2)}/m²</strong></div><div><span>Break-even</span><strong>${fmt(x.breakEven)}/m²</strong></div><div><span>Marktpuffer</span><strong>${x.marketBuffer.toFixed(1)} %</strong></div><div><span>Max. Landpreis</span><strong>${fmt(x.maxLand)}</strong></div></div>`:''}<div class="deal-foot"><small>${esc(x.reason)}</small><button class="text-btn edit-deal" data-id="${x.id||''}">Details</button></div></div><div class="score"><strong>${x.score??'?'}</strong><small>SCORE</small></div></article>`).join(''):'<div class="empty"><strong>Noch keine Opportunity bewertet</strong><p>Nutze „+ Opportunity prüfen“ oder „Beispielanalyse“ für die Präsentation.</p></div>'}
}

function buildFallbacks(){const region=$('regionFilter').value==='all'?'Basel-Stadt Basel-Landschaft Aargau Solothurn':$('regionFilter').value;const q=encodeURIComponent(`${$('searchKeywords').value} ${region} Schweiz`);const g=s=>'https://www.google.com/search?q='+encodeURIComponent(s);const base=`${$('searchKeywords').value} ${region} Schweiz`;const sources=[['Gesamtes Web','◎',g(base)],['Facebook Marketplace','f','https://www.facebook.com/marketplace/switzerland/search/?query='+q],['Tutti','T',g(`site:tutti.ch ${base}`)],['Comparis','C',g(`site:comparis.ch/immobilien ${base}`)],['ImmoScout24','I',g(`site:immoscout24.ch ${base}`)],['Homegate','H',g(`site:homegate.ch ${base}`)],['Newhome','N',g(`site:newhome.ch ${base}`)],['Makler & Projektentwickler','M',g(`${base} Immobilienmakler Projektentwicklung Baulandreserve Abbruchobjekt`)]];$('sourceGrid').innerHTML=sources.map(([n,i,u],idx)=>`<article class="source-card"><div class="source-head"><span class="source-icon">${i}</span><div><strong>${n}</strong><small>Suchbereich ${idx+1}</small></div></div><p>Kostenlose Vertiefungssuche in der Originalquelle.</p><a class="source-link" target="_blank" rel="noopener noreferrer" href="${u}">Suchbereich öffnen ↗</a></article>`).join('')}
async function startSearch(){const region=$('regionFilter').value==='all'?'Basel-Stadt Basel-Landschaft Aargau Solothurn':$('regionFilter').value;const budget=$('budgetFilter').value==='999'?'':$('budgetFilter').options[$('budgetFilter').selectedIndex].textContent;$('searchStatus').hidden=false;$('searchStatus').innerHTML='<strong>Suche läuft …</strong> Öffentliche Webtreffer werden kostenlos geprüft.';$('liveResults').innerHTML='';buildFallbacks();try{const url=`${BACKEND}?region=${encodeURIComponent(region)}&budget=${encodeURIComponent(budget)}&q=${encodeURIComponent($('searchKeywords').value)}`;const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const data=await r.json();if(data.results?.length){$('searchStatus').innerHTML=`<strong>${data.results.length} öffentliche Treffer gefunden.</strong> Treffer immer an der Originalquelle verifizieren.`;$('liveResults').innerHTML=data.results.slice(0,20).map(x=>`<article class="live-card"><h4>${esc(x.title)}</h4><p>${esc(x.snippet||'Keine Vorschau verfügbar.')}</p><div class="live-meta"><span>${esc(x.source)}</span><a href="${x.url}" target="_blank" rel="noopener noreferrer">Original öffnen ↗</a></div></article>`).join('')}else{$('searchStatus').innerHTML='<strong>Automatischer Gratis-Scan aktuell ohne verwertbare Treffer.</strong> Die direkten Suchbereiche darunter sind verfügbar. Es entstehen keine API-Kosten.'}}catch(e){$('searchStatus').innerHTML='<strong>Gratis-Live-Suche momentan nicht erreichbar.</strong> Nutze die direkten Suchbereiche darunter; die Markt- und Wirtschaftlichkeitsanalyse funktioniert vollständig.'}}

function openExample(){const ex={name:'Präsentationsbeispiel · Pratteln BL',region:'Basel-Landschaft',strategy:'Mehrfamilienhaus',area:1250,price:2100000,gfa:1900,sellable:1520,saleM2:8350,buildM2:3500,softPct:18,reservePct:7,acqPct:3,targetMargin:15,location:82,planning:82,architecture:85,risk:75,status:'analysed'};Object.entries(ex).forEach(([k,v])=>{const el=$(k);if(el)el.value=v});$('dialog').showModal();updatePreview()}

$('startSearchBtn').addEventListener('click',startSearch);$('searchKeywords').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();startSearch()}});$('addBtn').addEventListener('click',()=>{$('form').reset();$('dialog').showModal();updatePreview()});$('presentationBtn').addEventListener('click',openExample);$('closeBtn').addEventListener('click',()=>$('dialog').close());$('cancelBtn').addEventListener('click',()=>$('dialog').close());$('patchCloseBtn').addEventListener('click',markPatchSeen);$('resetBtn').addEventListener('click',()=>{$('regionFilter').value='all';$('budgetFilter').value='999';$('strategyFilter').value='all';$('marginFilter').value='0';$('liveResults').innerHTML='';$('sourceGrid').innerHTML='';$('searchStatus').hidden=true;render()});['regionFilter','budgetFilter','strategyFilter','marginFilter','sortFilter'].forEach(id=>$(id).addEventListener('change',render));['price','gfa','sellable','saleM2','buildM2','softPct','reservePct','acqPct','targetMargin','location','planning','architecture','risk'].forEach(id=>$(id).addEventListener('input',updatePreview));$('form').addEventListener('submit',e=>{e.preventDefault();const x=formData();x.id=Date.now().toString(36);state.items.unshift(x);save();$('dialog').close();render()});
$('appVersion').textContent='Beta '+APP_VERSION;render();showPatchNotes();registerUpdates();