const APP_VERSION='0.7';
const PATCH_NOTES={version:'0.7',date:'19.08.2026',title:'Beta 0.7 – Suchlauf in der App',notes:['„Suche starten“ verlässt die App nicht mehr.','Die missverständliche Bezeichnung „Quellen suchen“ wurde durch klare Suchbereiche ersetzt.','Die vier alten ImmoScout-Demoobjekte werden automatisch entfernt.','Alle acht Suchbereiche werden nach jedem Suchlauf gemeinsam angezeigt.','Eigene gespeicherte Grundstücke bleiben unverändert erhalten.']};
const PILOT_REGIONS=['Basel-Stadt','Basel-Landschaft','Aargau','Solothurn'];
const DEMO_NAMES=new Set(['Riehen BS · Bauland','Rümlingen BL · Bauland','Frick AG · Bauland','Oberdorf SO · Bauland']);
const loadedItems=JSON.parse(localStorage.getItem('structaScoutItems')||'[]');
const cleanedItems=loadedItems.filter(x=>!(x.status==='web'&&x.source==='ImmoScout24'&&DEMO_NAMES.has(x.name)));
const state={items:cleanedItems};
if(cleanedItems.length!==loadedItems.length)localStorage.setItem('structaScoutItems',JSON.stringify(cleanedItems));
const fmt=n=>new Intl.NumberFormat('de-CH',{style:'currency',currency:'CHF',maximumFractionDigits:0}).format(n);
const fmtNum=n=>new Intl.NumberFormat('de-CH').format(n);
const $=id=>document.getElementById(id);
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

const scoreOf=x=>{if(x.status==='web')return null;const invest=x.price+x.build+x.extra;const profit=x.revenue-invest;const margin=invest>0?profit/invest*100:0;const econ=Math.max(0,Math.min(100,margin*4));return Math.round(econ*.4+x.location*.25+x.planning*.2+x.risk*.15)};
const enrich=x=>{if(x.status==='web')return {...x,invest:x.price,profit:null,margin:null,score:null};const invest=x.price+x.build+x.extra;const profit=x.revenue-invest;const margin=invest?profit/invest*100:0;return {...x,invest,profit,margin,score:scoreOf(x)}};
const save=()=>localStorage.setItem('structaScoutItems',JSON.stringify(state.items));

function showPatchNotes(){const seen=localStorage.getItem('structaScoutSeenVersion');if(seen===APP_VERSION)return;$('patchTitle').textContent=`Was ist neu in ${PATCH_NOTES.title}?`;$('patchDate').textContent=PATCH_NOTES.date;$('patchNotes').innerHTML=PATCH_NOTES.notes.map(n=>`<div class="patch-item"><span>✓</span><p>${escapeHtml(n)}</p></div>`).join('');$('patchDialog').showModal();}
function markPatchSeen(){localStorage.setItem('structaScoutSeenVersion',APP_VERSION);$('patchDialog').close();}
async function registerUpdates(){if(!('serviceWorker' in navigator))return;try{const reg=await navigator.serviceWorker.register('./sw.js?v='+APP_VERSION);const trigger=()=>reg.update().catch(()=>{});trigger();document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')trigger()});window.addEventListener('focus',trigger);navigator.serviceWorker.addEventListener('controllerchange',()=>{if(sessionStorage.getItem('structaScoutReloading'))return;sessionStorage.setItem('structaScoutReloading','1');$('updateStatus').hidden=false;setTimeout(()=>location.reload(),250)});setInterval(trigger,15*60*1000);}catch(e){console.warn('Update-Prüfung nicht verfügbar',e)}}

function regionData(){const region=$('regionFilter').value;const regionText=region==='all'?'Basel-Stadt Basel-Landschaft Aargau Solothurn':region;return {region,regionText};}
function budgetData(){const sel=$('budgetFilter');if(sel.value==='999')return {text:'',value:null};return {text:sel.options[sel.selectedIndex].textContent.replace('bis ','').trim(),value:+sel.value*1000000};}
function google(q){return 'https://www.google.com/search?q='+encodeURIComponent(q)}

function buildSearches(){const {regionText}=regionData();const budget=budgetData();const keywords=($('searchKeywords').value||'Bauland Grundstück Entwicklungsobjekt Abbruchobjekt Baulandreserve').trim();const budgetText=budget.text?` ${budget.text}`:'';const base=`${keywords} kaufen ${regionText} Schweiz${budgetText}`;return [
{name:'Gesamtes öffentliches Web',icon:'◎',tag:'Suchbereich 1',desc:'Breite Websuche nach Grundstücken, Entwicklungsobjekten, Maklern und Projektentwicklern.',url:google(`${base} (Grundstück OR Bauland OR Entwicklungsobjekt OR Abbruchobjekt OR Baulandreserve)`)},
{name:'Facebook Marketplace',icon:'f',tag:'Suchbereich 2',desc:'Private und gewerbliche Angebote auf Facebook Marketplace. Anmeldung kann erforderlich sein.',url:'https://www.facebook.com/marketplace/switzerland/search/?query='+encodeURIComponent(`Bauland Grundstück ${regionText}`)},
{name:'Tutti',icon:'T',tag:'Suchbereich 3',desc:'Grundstücke und Immobilienangebote auf Tutti.',url:google(`site:tutti.ch ${base}`)},
{name:'Comparis',icon:'C',tag:'Suchbereich 4',desc:'Immobilienangebote, die über Comparis auffindbar sind.',url:google(`site:comparis.ch/immobilien ${base}`)},
{name:'ImmoScout24',icon:'I',tag:'Suchbereich 5',desc:'Bauland, Grundstücke und Entwicklungsobjekte auf ImmoScout24.',url:google(`site:immoscout24.ch ${base}`)},
{name:'Homegate',icon:'H',tag:'Suchbereich 6',desc:'Bauland, Mehrfamilienhäuser und Entwicklungsobjekte auf Homegate.',url:google(`site:homegate.ch ${base}`)},
{name:'Newhome',icon:'N',tag:'Suchbereich 7',desc:'Zusätzliche Schweizer Immobilienangebote auf Newhome.',url:google(`site:newhome.ch ${base}`)},
{name:'Makler & Projektentwickler',icon:'M',tag:'Suchbereich 8',desc:'Lokale Makler, Immobilienfirmen, Projektentwickler, Baulandreserven und Abbruchobjekte.',url:google(`(${keywords}) ${regionText} Schweiz (Immobilienmakler OR "Immobilien AG" OR "Immobilien GmbH" OR Projektentwicklung OR Baulandreserve OR Abbruchobjekt)${budgetText}`)}
];}

function setupSearchUi(){const title=document.querySelector('.search-title h3');const intro=document.querySelector('.search-title p');const count=document.querySelector('.source-count');const hint=document.querySelector('.search-hint');if(title)title.textContent='Grundstückssuche';if(intro)intro.textContent='Ein Suchlauf berücksichtigt immer Web, Facebook, Tutti, Comparis, ImmoScout24, Homegate, Newhome sowie Makler- und Projektentwicklerseiten.';if(count)count.textContent='8 Suchbereiche';if(hint)hint.innerHTML='<strong>Wichtig:</strong> Die App bleibt beim Start des Suchlaufs geöffnet. Externe Portale öffnen sich nur, wenn du einen Suchbereich bewusst auswählst.';}

function renderSearchSources(){const sources=buildSearches();$('sourceGrid').innerHTML=sources.map(s=>`<article class="source-card"><div class="source-head"><span class="source-icon">${escapeHtml(s.icon)}</span><div><strong>${escapeHtml(s.name)}</strong><small>${escapeHtml(s.tag)}</small></div></div><p>${escapeHtml(s.desc)}</p><a class="source-link" href="${s.url}" target="_blank" rel="noopener noreferrer">Suchbereich öffnen ↗</a></article>`).join('');}
function startSearch(){renderSearchSources();$('searchStatus').hidden=false;$('searchStatus').innerHTML='<strong>Suchlauf vorbereitet: 8 von 8 Suchbereichen.</strong><br>Du bleibst in der App. Wähle unten nur dann einen Suchbereich aus, wenn du die Originaltreffer dieses Portals ansehen möchtest.';$('sourceGrid').scrollIntoView({behavior:'smooth',block:'start'});}

function render(){let items=state.items.filter(x=>PILOT_REGIONS.includes(x.region)).map(enrich);const region=$('regionFilter').value,budget=+$('budgetFilter').value*1e6,strat=$('strategyFilter').value,minMargin=+$('marginFilter').value;items=items.filter(x=>(region==='all'||x.region===region)&&(strat==='all'||x.strategy===strat)&&x.price<=budget&&(x.margin===null?minMargin===0:x.margin>=minMargin));const sort=$('sortFilter').value;items.sort((a,b)=>{if(sort==='price')return a.price-b.price;const av=a[sort]??-Infinity,bv=b[sort]??-Infinity;return bv-av});$('countKpi').textContent=items.length;const analysed=items.filter(x=>x.status!=='web');$('marginKpi').textContent=analysed.length?(analysed.reduce((s,x)=>s+x.margin,0)/analysed.length).toFixed(1)+' %':'offen';$('profitKpi').textContent=analysed.length?fmt(analysed.reduce((s,x)=>s+x.profit,0)/analysed.length):'offen';const scored=analysed.filter(x=>x.score!==null);const best=scored.length?Math.max(...scored.map(x=>x.score)):null;$('scoreKpi').textContent=best??'–';$('topScore').textContent=best??'–';$('list').innerHTML=items.length?items.map(x=>{if(x.status==='web')return `<article class="card web-card"><div><div class="source-row"><span class="source-badge">WEB-FUND</span><span class="found-date">gefunden ${escapeHtml(x.found||'')}</span></div><h4>${escapeHtml(x.name)}</h4><div class="meta"><span>${escapeHtml(x.region)}</span><span>${escapeHtml(x.strategy)}</span><span>${fmtNum(x.area)} m²</span><span>${fmt(Math.round(x.price/x.area))}/m²</span></div><div class="metrics"><span class="metric">Kaufpreis<strong>${fmt(x.price)}</strong></span><span class="metric">Baukosten<strong>noch offen</strong></span><span class="metric">Gewinn<strong>noch offen</strong></span><span class="metric">Marge<strong>noch offen</strong></span></div><div class="web-actions"><span>Quelle: ${escapeHtml(x.source||'Web')}</span>${x.url?`<a href="${x.url}" target="_blank" rel="noopener noreferrer">Inserat öffnen ↗</a>`:''}</div></div><div class="score pending"><strong>?</strong><small>VORPRÜFUNG</small></div></article>`;return `<article class="card"><div><h4>${escapeHtml(x.name)}</h4><div class="meta"><span>${escapeHtml(x.region)}</span><span>${escapeHtml(x.strategy)}</span><span>${fmtNum(x.area)} m²</span></div><div class="metrics"><span class="metric">Kaufpreis<strong>${fmt(x.price)}</strong></span><span class="metric">Investition<strong>${fmt(x.invest)}</strong></span><span class="metric">Gewinn<strong>${fmt(x.profit)}</strong></span><span class="metric">Marge<strong>${x.margin.toFixed(1)} %</strong></span></div></div><div class="score"><strong>${x.score}</strong><small>SCORE</small></div></article>`}).join(''):'<div class="empty"><strong>Noch keine Grundstücke gespeichert</strong><p>Starte oben einen Suchlauf oder erfasse ein interessantes Objekt.</p></div>';}

setupSearchUi();
$('startSearchBtn').addEventListener('click',startSearch);
$('searchKeywords').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();startSearch()}});
$('addBtn').addEventListener('click',()=>$('dialog').showModal());
$('closeBtn').addEventListener('click',()=>$('dialog').close());
$('cancelBtn').addEventListener('click',()=>$('dialog').close());
$('patchCloseBtn').addEventListener('click',markPatchSeen);
$('resetBtn').addEventListener('click',()=>{$('regionFilter').value='all';$('budgetFilter').value='999';$('strategyFilter').value='all';$('marginFilter').value='0';$('searchStatus').hidden=true;$('sourceGrid').innerHTML='';render()});
['regionFilter','budgetFilter','strategyFilter','marginFilter','sortFilter'].forEach(id=>$(id).addEventListener('change',render));
$('form').addEventListener('submit',e=>{e.preventDefault();const region=$('region').value;if(!PILOT_REGIONS.includes(region)){alert('Aktuell sind nur Basel-Stadt, Basel-Landschaft, Aargau und Solothurn als Pilotregionen freigeschaltet.');return;}state.items.unshift({name:$('name').value.trim(),region,strategy:$('strategy').value,area:+$('area').value,price:+$('price').value,build:+$('build').value,extra:+$('extra').value,revenue:+$('revenue').value,location:+$('location').value,planning:+$('planning').value,risk:+$('risk').value,status:'analysed'});save();e.target.reset();$('dialog').close();render()});

$('appVersion').textContent='Beta '+APP_VERSION;
render();
showPatchNotes();
registerUpdates();