const PIPELINE_VERSION='0.16';
(function(){
  const $=id=>document.getElementById(id);
  const STATUS={
    new:{label:'Neu geprüft',icon:'●',className:'new'},
    deepen:{label:'Vertiefen',icon:'↗',className:'deepen'},
    favorite:{label:'Favorit',icon:'★',className:'favorite'},
    rejected:{label:'Ausgeschieden',icon:'×',className:'rejected'}
  };
  let statusFilter='active';
  let lastSavedId=null;
  let baseRender=null;

  function injectStyles(){
    if($('pipelineV2Styles'))return;
    const s=document.createElement('style');s.id='pipelineV2Styles';s.textContent=`
      .pipeline-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:-4px 0 14px}.pipe-tab{border:1px solid #dce4ef;background:#fff;color:#536177;border-radius:999px;padding:7px 10px;font-size:11px;font-weight:800;cursor:pointer}.pipe-tab.active{background:#173d63;color:#fff;border-color:#173d63}.pipe-tab b{margin-left:5px}
      .pipeline-note{font-size:11px;color:#738096;margin:-8px 0 12px;line-height:1.45}.pipeline-card{display:block!important;position:relative;padding:16px!important}.pipeline-card.highlight{outline:3px solid rgba(38,71,163,.18);box-shadow:0 10px 30px rgba(38,71,163,.12)}
      .pipe-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.pipe-head-main{min-width:0}.pipe-head h4{font-size:16px;margin:7px 0 4px}.pipe-badges{display:flex;gap:6px;flex-wrap:wrap}.pipe-status,.pipe-decision,.pipe-basis{display:inline-flex;align-items:center;border-radius:999px;padding:4px 7px;font-size:9px;font-weight:900;letter-spacing:.03em}.pipe-status.new{background:#eef2f7;color:#596579}.pipe-status.deepen{background:#fff3d8;color:#8a5b00}.pipe-status.favorite{background:#eaf0ff;color:#2647a3}.pipe-status.rejected{background:#fdecec;color:#9d2c2c}.pipe-decision.buy{background:#e9f8ef;color:#17683c}.pipe-decision.check{background:#fff3d8;color:#8a5b00}.pipe-decision.no{background:#fdecec;color:#9d2c2c}.pipe-basis{background:#f2f4f8;color:#667386}
      .pipe-score{flex:0 0 62px;height:62px;border-radius:14px;background:#eaf0ff;color:#2647a3;display:grid;place-items:center;text-align:center}.pipe-score strong{font-size:22px;line-height:1}.pipe-score small{font-size:8px;font-weight:900}.pipe-meta{display:flex;gap:8px;flex-wrap:wrap;color:#738096;font-size:10px;margin-top:4px}.pipe-metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:7px;margin-top:12px}.pipe-metric{background:#f6f8fb;border-radius:9px;padding:8px}.pipe-metric span{display:block;color:#7a8594;font-size:9px}.pipe-metric strong{display:block;color:#223148;font-size:12px;margin-top:3px;word-break:break-word}.pipe-reason{margin-top:10px;padding:9px 10px;border-radius:9px;background:#f7f9fc;color:#536177;font-size:10px;line-height:1.4}.pipe-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:11px;padding-top:10px;border-top:1px solid #edf0f4}.pipe-action{border:0;border-radius:8px;padding:8px 10px;font-size:10px;font-weight:800;cursor:pointer;background:#edf2f8;color:#29415f}.pipe-action.primary{background:#2647a3;color:#fff}.pipe-action.favorite{background:#eaf0ff;color:#2647a3}.pipe-action.reject{background:#fdeeee;color:#963737}.pipe-action.delete{margin-left:auto;background:transparent;color:#9a5960}.pipe-source{color:#2647a3;text-decoration:none;font-size:10px;font-weight:800;align-self:center}.pipeline-empty{padding:28px 18px;text-align:center;border:1px dashed #cdd7e5;border-radius:12px;color:#738096}.pipeline-empty strong{display:block;color:#43536a;margin-bottom:5px}.pipeline-empty button{margin-top:10px}
      @media(max-width:760px){.pipe-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.pipe-score{flex-basis:54px;height:54px}.pipe-actions{display:grid;grid-template-columns:1fr 1fr}.pipe-action{min-height:38px}.pipe-action.delete{margin-left:0}.pipeline-card{padding:13px!important}.pipe-head h4{font-size:14px}}
    `;document.head.appendChild(s);
  }
  function fmtCHF(n){return new Intl.NumberFormat('de-CH',{style:'currency',currency:'CHF',maximumFractionDigits:0}).format(Number(n)||0)}
  function escP(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function allItems(){try{return state.items.map(calculate)}catch{return []}}
  function itemStatus(x){return x.pipelineStatus&&STATUS[x.pipelineStatus]?x.pipelineStatus:'new'}
  function activeItems(items){return items.filter(x=>itemStatus(x)!=='rejected')}
  function setStatus(id,status){const item=state.items.find(x=>x.id===id);if(!item)return;item.pipelineStatus=status;item.pipelineUpdated=new Date().toISOString();save();render();}
  function removeItem(id){const item=state.items.find(x=>x.id===id);if(!item)return;if(!confirm('Diese Opportunity wirklich löschen?'))return;const i=state.items.findIndex(x=>x.id===id);if(i>=0)state.items.splice(i,1);save();render();}
  function counts(items){return {all:items.length,active:items.filter(x=>itemStatus(x)!=='rejected').length,new:items.filter(x=>itemStatus(x)==='new').length,deepen:items.filter(x=>itemStatus(x)==='deepen').length,favorite:items.filter(x=>itemStatus(x)==='favorite').length,rejected:items.filter(x=>itemStatus(x)==='rejected').length}}
  function installToolbar(items){const panel=document.querySelector('.opportunities');const title=panel?.querySelector('.panel-title');if(!panel||!title)return;let note=$('pipelineV2Note');if(!note){note=document.createElement('div');note.id='pipelineV2Note';note.className='pipeline-note';note.textContent='Gespeicherte Projekte bleiben hier unabhängig von den Suchfiltern sichtbar. Markiere, welche Opportunities wir vertiefen wollen.';title.insertAdjacentElement('afterend',note)}let bar=$('pipelineToolbar');if(!bar){bar=document.createElement('div');bar.id='pipelineToolbar';bar.className='pipeline-toolbar';note.insertAdjacentElement('afterend',bar)}const c=counts(items);const defs=[['active','Aktiv',c.active],['new','Neu',c.new],['deepen','Vertiefen',c.deepen],['favorite','Favoriten',c.favorite],['rejected','Ausgeschieden',c.rejected],['all','Alle',c.all]];bar.innerHTML=defs.map(([v,l,n])=>`<button type="button" class="pipe-tab ${statusFilter===v?'active':''}" data-pipe-filter="${v}">${l}<b>${n}</b></button>`).join('')}
  function filtered(items){if(statusFilter==='all')return items;if(statusFilter==='active')return items.filter(x=>itemStatus(x)!=='rejected');return items.filter(x=>itemStatus(x)===statusFilter)}
  function sorted(items){const sort=$('sortFilter')?.value||'score';return [...items].sort((a,b)=>sort==='price'?(Number(a.price)||0)-(Number(b.price)||0):(Number(b[sort])||-Infinity)-(Number(a[sort])||-Infinity))}
  function updateKpis(items){const active=activeItems(items),analysed=active.filter(x=>x.margin!=null);if($('countKpi'))$('countKpi').textContent=active.length;if($('countKpi')?.nextElementSibling)$('countKpi').nextElementSibling.textContent=`${items.length} gespeichert · ${counts(items).rejected} ausgeschieden`;if($('marginKpi'))$('marginKpi').textContent=analysed.length?(analysed.reduce((s,x)=>s+x.margin,0)/analysed.length).toFixed(1)+' %':'offen';if($('profitKpi'))$('profitKpi').textContent=analysed.length?fmtCHF(analysed.reduce((s,x)=>s+x.profit,0)/analysed.length):'offen';const best=analysed.length?Math.max(...analysed.map(x=>Number(x.score)||0)):null;if($('scoreKpi'))$('scoreKpi').textContent=best??'–';if($('topScore'))$('topScore').textContent=best??'–'}
  function card(x){const status=itemStatus(x),st=STATUS[status],loc=x.locationAnalysis,score=x.score??null,basis=x.basis?.label||'Grobe Vorprüfung';return `<article class="card pipeline-card ${x.id===lastSavedId?'highlight':''}" data-pipeline-id="${escP(x.id)}"><div class="pipe-head"><div class="pipe-head-main"><div class="pipe-badges"><span class="pipe-status ${st.className}">${st.icon} ${st.label}</span><span class="pipe-decision ${x.decisionClass||'check'}">${escP(x.decision||'DATEN FEHLEN')}</span><span class="pipe-basis">${escP(basis)}</span></div><h4>${escP(x.name)}</h4><div class="pipe-meta"><span>${escP(x.region)}</span><span>${escP(x.strategy)}</span><span>${Number(x.area||0).toLocaleString('de-CH')} m² Land</span>${loc?.score?`<span>Standort ${loc.score}/100${loc.confidence?` · ${escP(loc.confidence.label||'')}`:''}</span>`:''}</div></div><div class="pipe-score"><div><strong>${score??'?'}</strong><small>SCORE</small></div></div></div><div class="pipe-metrics"><div class="pipe-metric"><span>Kaufpreis</span><strong>${fmtCHF(x.price)}</strong></div><div class="pipe-metric"><span>Gesamtinvestition</span><strong>${x.invest!=null?fmtCHF(x.invest):'offen'}</strong></div><div class="pipe-metric"><span>Gewinnpotenzial</span><strong>${x.profit!=null?fmtCHF(x.profit):'offen'}</strong></div><div class="pipe-metric"><span>Projektmarge</span><strong>${x.margin!=null?x.margin.toFixed(1)+' %':'offen'}</strong></div><div class="pipe-metric"><span>Max. Landpreis</span><strong>${x.maxLand!=null?fmtCHF(x.maxLand):'offen'}</strong></div></div><div class="pipe-reason">${escP(x.reason||'Noch keine vollständige Bewertung vorhanden.')}</div><div class="pipe-actions"><button type="button" class="pipe-action primary" data-pipe-action="details">Details / Annahmen</button>${status!=='deepen'?'<button type="button" class="pipe-action" data-pipe-action="deepen">Vertiefen</button>':''}${status!=='favorite'?'<button type="button" class="pipe-action favorite" data-pipe-action="favorite">★ Favorit</button>':''}${status!=='rejected'?'<button type="button" class="pipe-action reject" data-pipe-action="rejected">Ausscheiden</button>':'<button type="button" class="pipe-action" data-pipe-action="new">Reaktivieren</button>'}${x.sourceUrl?`<a class="pipe-source" href="${escP(x.sourceUrl)}" target="_blank" rel="noopener noreferrer">Originalquelle ↗</a>`:''}<button type="button" class="pipe-action delete" data-pipe-action="delete">Löschen</button></div></article>`}
  function renderPipeline(){const items=allItems();installToolbar(items);updateKpis(items);const target=$('list');if(!target)return;const visible=sorted(filtered(items));if(!visible.length){target.innerHTML=`<div class="pipeline-empty"><strong>${items.length?'Keine Projekte in diesem Status':'Noch keine Opportunity gespeichert'}</strong><span>${items.length?'Wähle oben einen anderen Pipeline-Status.':'Suche ein Grundstück, tippe auf „Jetzt prüfen“ und danach auf „Bewerten & speichern“.'}</span>${items.length?'':'<button type="button" class="btn primary" id="pipelineGoSearch">Zur Grundstückssuche</button>'}</div>`;return}target.innerHTML=visible.map(card).join('');if(lastSavedId){const el=target.querySelector(`[data-pipeline-id="${CSS.escape(lastSavedId)}"]`);if(el)setTimeout(()=>el.scrollIntoView({behavior:'smooth',block:'center'}),80);setTimeout(()=>{lastSavedId=null;target.querySelectorAll('.highlight').forEach(e=>e.classList.remove('highlight'))},2200)}}
  function wrapRender(){if(baseRender||typeof render!=='function')return;baseRender=render;render=function(){baseRender();renderPipeline()}}
  function bind(){const panel=document.querySelector('.opportunities');if(panel&&panel.dataset.pipeV2!=='1'){panel.dataset.pipeV2='1';panel.addEventListener('click',e=>{const tab=e.target.closest('[data-pipe-filter]');if(tab){statusFilter=tab.dataset.pipeFilter;renderPipeline();return}const btn=e.target.closest('[data-pipe-action]');if(!btn)return;const cardEl=btn.closest('[data-pipeline-id]'),id=cardEl?.dataset.pipelineId;if(!id)return;const action=btn.dataset.pipeAction;if(action==='details'){const item=state.items.find(x=>x.id===id);if(item)populateExisting(item)}else if(action==='delete')removeItem(id);else setStatus(id,action)})}const form=$('form');if(form&&form.dataset.pipeV2Submit!=='1'){form.dataset.pipeV2Submit='1';form.addEventListener('submit',()=>{const before=new Set(state.items.map(x=>x.id));setTimeout(()=>{const added=state.items.find(x=>!before.has(x.id));if(added){if(!added.pipelineStatus)added.pipelineStatus='new';save();lastSavedId=added.id}render();},60)})}}
  function install(){injectStyles();wrapRender();bind();renderPipeline()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
