const LOCAL_VERSION='0.11';
const RELEASE_ID='0.11-r1';
const RELEASE_NOTES={
  title:'Beta 0.11 – Automatische Grobkosten',
  date:'19.08.2026',
  notes:[
    'Objektspezifische Sonderkosten werden in der Erstprüfung automatisch grob geschätzt.',
    'Inseratshinweise wie Bestand, Schadstoffrisiko, Hanglage, fehlende Baureife, Wasser oder Altlasten aktivieren passende Risikoreserven.',
    'Abbruch, Aushub, Erschliessung und Vermarktung orientieren sich an öffentlich zugänglichen Schweizer Richtwerten; projektspezifische Reserven bleiben klar als Grobschätzung markiert.',
    'Bei Web-Funden setzt der Scout zusätzlich eine erste BGF-/Nutzflächenannahme und einen groben kantonalen Marktbenchmark, damit sofort eine Vorprüfung möglich ist.',
    'Alle automatisch gesetzten Kosten können im manuellen Modus überschrieben werden.',
    '0 CHF laufende Softwarekosten, sichtbare Version, Patchnotes und Pull-to-Refresh bleiben unverändert.'
  ]
};
let updateInProgress=false;
async function clearScoutCaches(){if(!('caches' in window))return;const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('structa-scout-')).map(k=>caches.delete(k)));}
async function forceLatestVersion(targetVersion=LOCAL_VERSION){if(updateInProgress)return;updateInProgress=true;try{const status=document.getElementById('updateStatus');if(status){status.textContent='Neue Version wird geladen …';status.hidden=false;}const regs=('serviceWorker' in navigator)?await navigator.serviceWorker.getRegistrations():[];await Promise.all(regs.map(r=>r.update().catch(()=>{})));await clearScoutCaches();const u=new URL(location.href);u.searchParams.set('v',targetVersion);u.searchParams.set('refresh',Date.now().toString());location.replace(u.toString());}catch(e){console.warn('Update konnte nicht erzwungen werden',e);updateInProgress=false;}}
async function checkRemoteVersion(){try{const r=await fetch('./version.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)return;const data=await r.json();if(data.version&&data.version!==LOCAL_VERSION)await forceLatestVersion(data.version);}catch(e){console.warn('Versionsprüfung nicht verfügbar',e);}}
async function registerServiceWorker(){if(!('serviceWorker' in navigator))return;try{const reg=await navigator.serviceWorker.register('./sw.js?v='+LOCAL_VERSION);reg.update().catch(()=>{});}catch(e){console.warn('Service Worker nicht verfügbar',e);}}
function injectUxStyles(){if(document.getElementById('structaUxStyles'))return;const style=document.createElement('style');style.id='structaUxStyles';style.textContent=`.version-pill{border:1px solid #cfdaf0;background:#fff;color:#2647a3;border-radius:999px;padding:9px 12px;font-size:12px;font-weight:900;letter-spacing:.03em;cursor:pointer;box-shadow:0 4px 12px rgba(38,71,163,.08);white-space:nowrap}.version-pill:hover{background:#f4f7ff}.pull-refresh{position:fixed;z-index:1200;left:50%;top:-58px;transform:translateX(-50%);background:#173d63;color:#fff;border-radius:999px;padding:10px 16px;font-size:12px;font-weight:800;box-shadow:0 10px 28px rgba(23,61,99,.28);transition:top .18s ease,opacity .18s ease;opacity:0;pointer-events:none}.pull-refresh.visible{top:14px;opacity:1}.pull-refresh.ready{background:#2647a3}.verified-live-card{border-left:4px solid #2647a3}.verified-badge{display:inline-flex;align-items:center;gap:5px;background:#e9f8ef;color:#17683c;border-radius:999px;padding:4px 8px;font-size:10px;font-weight:900;letter-spacing:.04em;margin-bottom:7px}.verified-address{font-size:12px;color:#667386;margin:0 0 8px}.verified-metrics{display:flex;gap:8px;flex-wrap:wrap;margin:9px 0}.verified-metrics span{background:#f4f7fb;border-radius:8px;padding:7px 9px;font-size:11px;color:#65758a}.verified-metrics strong{color:#23344f;margin-left:4px}.verified-note{font-size:11px!important;color:#738096!important}.verified-live-card .live-meta{border-top:1px solid #edf0f4;padding-top:9px}.verified-source{font-weight:800;color:#405675}.market-actions{display:flex;gap:10px;align-items:center}.market-check-btn{padding:8px 11px;font-size:12px}@media(max-width:640px){.top-actions{flex-wrap:wrap}.version-pill{width:100%;text-align:center;order:-1}.verified-metrics{display:grid;grid-template-columns:1fr 1fr}.verified-live-card .live-meta{align-items:flex-start;flex-direction:column}.market-actions{width:100%;justify-content:space-between}}`;document.head.appendChild(style);}
function setVisibleVersion(){const sidebar=document.getElementById('appVersion');if(sidebar)sidebar.textContent='Beta '+LOCAL_VERSION;let badge=document.getElementById('versionBadge');if(!badge){const actions=document.querySelector('.top-actions');if(actions){badge=document.createElement('button');badge.type='button';badge.id='versionBadge';badge.className='version-pill';badge.title='Patchnotes anzeigen';actions.prepend(badge);}}if(badge){badge.textContent='Beta '+LOCAL_VERSION+' · Was ist neu?';badge.onclick=()=>showReleaseNotes(true);}}
function fillReleaseNotes(){const title=document.getElementById('patchTitle'),date=document.getElementById('patchDate'),notes=document.getElementById('patchNotes');if(!title||!date||!notes)return false;title.textContent='Was ist neu in '+RELEASE_NOTES.title+'?';date.textContent=RELEASE_NOTES.date;const safe=s=>String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));notes.innerHTML=RELEASE_NOTES.notes.map(n=>`<div class="patch-item"><span>✓</span><p>${safe(n)}</p></div>`).join('');return true;}
function showReleaseNotes(force=false){if(!force&&localStorage.getItem('structaScoutReleaseSeen')===RELEASE_ID)return;if(!fillReleaseNotes())return;const dialog=document.getElementById('patchDialog');if(dialog&&!dialog.open){try{dialog.showModal();}catch(e){console.warn('Patchnotes konnten nicht geöffnet werden',e);}}}
function bindReleaseClose(){const close=document.getElementById('patchCloseBtn');if(!close||close.dataset.releaseBound==='1')return;close.dataset.releaseBound='1';close.addEventListener('click',()=>{localStorage.setItem('structaScoutReleaseSeen',RELEASE_ID);const dialog=document.getElementById('patchDialog');if(dialog?.open)dialog.close();});}
function installPullToRefresh(){if(document.getElementById('pullRefreshIndicator'))return;const indicator=document.createElement('div');indicator.id='pullRefreshIndicator';indicator.className='pull-refresh';indicator.textContent='Zum Aktualisieren nach unten ziehen';document.body.appendChild(indicator);let startY=null,pull=0,tracking=false;document.addEventListener('touchstart',e=>{if(window.scrollY<=0&&e.touches?.length===1){startY=e.touches[0].clientY;pull=0;tracking=true;}},{passive:true});document.addEventListener('touchmove',e=>{if(!tracking||startY===null||!e.touches?.length)return;pull=Math.max(0,e.touches[0].clientY-startY);if(pull>12){indicator.classList.add('visible');if(pull>=75){indicator.classList.add('ready');indicator.textContent='Loslassen zum Aktualisieren';}else{indicator.classList.remove('ready');indicator.textContent='Zum Aktualisieren weiterziehen';}}},{passive:true});document.addEventListener('touchend',async()=>{if(!tracking)return;const refresh=pull>=75&&window.scrollY<=2;tracking=false;startY=null;if(refresh){indicator.classList.add('visible','ready');indicator.textContent='Aktualisiere …';await forceLatestVersion(LOCAL_VERSION);return;}indicator.classList.remove('visible','ready');setTimeout(()=>indicator.textContent='Zum Aktualisieren nach unten ziehen',180);},{passive:true});}
const chf=n=>new Intl.NumberFormat('de-CH',{style:'currency',currency:'CHF',maximumFractionDigits:0}).format(Number(n)||0);const intFmt=n=>new Intl.NumberFormat('de-CH',{maximumFractionDigits:0}).format(Number(n)||0);const safeText=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function verifiedFilter(items){const regionEl=document.getElementById('regionFilter'),budgetEl=document.getElementById('budgetFilter');const region=regionEl?.value||'all',budget=budgetEl?.value==='999'?Infinity:(Number(budgetEl?.value||999)*1000000);return items.filter(x=>(region==='all'||x.region===region)&&(!x.price||x.price<=budget));}
function renderVerifiedResults(data){const target=document.getElementById('liveResults'),status=document.getElementById('searchStatus');if(!target||!status)return;const items=verifiedFilter(data.items||[]);window.__structaVerifiedItems=items;if(!items.length){target.innerHTML='';status.hidden=false;status.innerHTML=`<strong>Keine verifizierten Angebote im aktuellen Filter.</strong> Stand ${safeText(data.updated||'')}. Erhöhe das Budget oder wähle eine weitere Region.`;return;}target.innerHTML=items.map((x,idx)=>{const ppm=x.area&&x.price?Math.round(x.price/x.area):null;return `<article class="live-card verified-live-card"><span class="verified-badge">✓ VERIFIZIERTER WEB-FUND</span><h4>${safeText(x.title)}</h4><p class="verified-address">${safeText(x.address)} · ${safeText(x.region)}</p><div class="verified-metrics"><span>Kaufpreis <strong>${x.price?chf(x.price):'auf Anfrage'}</strong></span><span>Grundstück <strong>${intFmt(x.area)} m²</strong></span>${ppm?`<span>Landpreis <strong>${chf(ppm)}/m²</strong></span>`:''}${x.zone?`<span>Zone <strong>${safeText(x.zone)}</strong></span>`:''}</div><p class="verified-note">${safeText(x.note||'')}</p><div class="live-meta"><span class="verified-source">Quelle: ${safeText(x.source)}</span><div class="market-actions"><a href="${x.url}" target="_blank" rel="noopener noreferrer">Originalquelle ↗</a><button type="button" class="btn primary market-check-btn" data-market-index="${idx}">Jetzt prüfen</button></div></div></article>`;}).join('');status.hidden=false;status.innerHTML=`<strong>${items.length} passende Marktangebote.</strong> Marktstand ${safeText(data.updated||'')}. „Jetzt prüfen“ startet die automatische Grobkosten- und Wirtschaftlichkeitsprüfung.`;}
function installMarketCheckHandler(){const target=document.getElementById('liveResults');if(!target||target.dataset.checkBound==='1')return;target.dataset.checkBound='1';target.addEventListener('click',e=>{const btn=e.target.closest('.market-check-btn');if(!btn)return;const item=(window.__structaVerifiedItems||[])[Number(btn.dataset.marketIndex)];if(item&&typeof window.openMarketOpportunity==='function')window.openMarketOpportunity(item);});}
async function runVerifiedMarketSearch(e){if(e){e.preventDefault();e.stopImmediatePropagation();}const status=document.getElementById('searchStatus'),target=document.getElementById('liveResults');if(status){status.hidden=false;status.innerHTML='<strong>Markt wird geprüft …</strong> Verifizierte Web-Funde werden nach Region und Budget gefiltert.';}if(target)target.innerHTML='';try{const r=await fetch('./market-data.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('market '+r.status);const data=await r.json();renderVerifiedResults(data);if(typeof buildFallbacks==='function')try{buildFallbacks();}catch{}}catch(err){console.warn('Marktdaten nicht verfügbar',err);if(status)status.innerHTML='<strong>Marktstand konnte gerade nicht geladen werden.</strong> Bitte nach unten ziehen zum Aktualisieren oder die direkten Suchbereiche verwenden.';if(typeof buildFallbacks==='function')try{buildFallbacks();}catch{}}}
function installVerifiedSearch(){const btn=document.getElementById('startSearchBtn');if(btn&&btn.dataset.verifiedBound!=='1'){btn.dataset.verifiedBound='1';btn.addEventListener('click',runVerifiedMarketSearch,true);}const input=document.getElementById('searchKeywords');if(input&&input.dataset.verifiedBound!=='1'){input.dataset.verifiedBound='1';input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();e.stopImmediatePropagation();runVerifiedMarketSearch();}},true);}}
function initReleaseUx(){injectUxStyles();setVisibleVersion();bindReleaseClose();installPullToRefresh();installVerifiedSearch();installMarketCheckHandler();registerServiceWorker();showReleaseNotes(false);}
window.addEventListener('load',()=>{initReleaseUx();checkRemoteVersion();setInterval(checkRemoteVersion,5*60*1000);});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')checkRemoteVersion();});window.addEventListener('focus',checkRemoteVersion);